// types/user.ts
export interface User {
  id: number;
  is_bvn: number;
  type: string;
  email: string;
  first_name: string;
  middle_name: string;
  last_name: string;
  migration_origin: string;
  opening_balance_au: string;
  opening_balance_ng: string;
  phone: string;
  account_number: string;
  gender: string | null;
  registered_on: string | null;
  is_verified: number;
  is_active: number;
  created_at: string;
  updated_at: string;
  email_verified_at: string | null;
  is_phone_verified: number;
  off_login_email_notification: number;
  gold_account_number: string | null;
  dukia_account_number: string | null;
  verification_code: string | null;
  zip_code: string | null;
  city: string | null;
  state: string | null;
  nationality: string | null;
  country: string | null;
  address_line_1: string | null;
  address_line_2: string | null;
  birthday: string | null;
  occupation: string | null;
  source_of_income: string | null;
  tax_identification_number: string | null;
  fatca: string | null;
  approved_at: string | null;
  approved_by: string | null;
  corporate_meta: string | null;
  phone2: string | null;
  email2: string | null;
  last_login: string | null;
  opening_balance_au_oz: string;
  referral_code: string | null;
  my_ref: string | null;
  company_name: string | null;
  company_type: string | null;
  company_registered_address: string | null;
  company_contact_telephone: string | null;
  company_contact_email: string | null;
  company_date_of_incorporation: string | null;
  company_country_of_incorporation: string | null;
  first_name2: string | null;
  middle_name2: string | null;
  last_name2: string | null;
  nationality2: string | null;
  gender2: string | null;
  birthday2: string | null;
  is_verified2: string | null;
  company_phone: string | null;
  company_registration_number: string | null;
  company_tax_identification_number: string | null;
  email_verification_link: string | null;
  bank_account_bank_name: string;
  bank_account_name: string;
  bank_account_number: string;
}
