import { AccountTypes, formFields } from "@/typings/landingPage/auth";

export const accountType: AccountTypes = [
  {
    id: "individual",
    icon: "",
    name: "Individual Account",
    text: "Lorem ipsum dolor sit amet consectetur.",
  },
  {
    id: "joint",
    icon: "",
    name: "Joint Account",
    text: "Lorem ipsum dolor sit amet consectetur.",
  },
  {
    id: "corporate",
    icon: "",
    name: "Corporate Account",
    text: "Lorem ipsum dolor sit amet consectetur.",
  },
];

export const formFieldsArray: formFields[] = [
  {
    accountType: "individual",
    fields: [
      {
        label: "First Name",
        name: "first_name",
        type: "text",
        placeholder: "Tunde",
        required: true,
      },
      {
        label: "Middle Name",
        name: "middle_name",
        type: "text",
        placeholder: "Ayoola",
        required: false,
      },
      {
        label: "Last Name",
        name: "last_name",
        type: "text",
        placeholder: "Fagbemi",
        required: true,
      },
      {
        label: "Email Address",
        name: "email",
        type: "email",
        placeholder: "ta***@****.com",
        required: true,
      },
      {
        label: "Phone Number",
        name: "phone",
        type: "tel",
        placeholder: "+234**********",
        required: true,
      },
      {
        label: "Nationality",
        name: "nationality",
        type: "text",
        placeholder: "Nigerian",
        required: true,
      },
      {
        label: "Gender",
        name: "gender",
        type: "select",
        placeholder: "Male/Female",
        options: [
          {
            value: "male",
            label: "Male",
          },
          {
            value: "female",
            label: "Female",
          },
        ],
        required: true,
      },
      {
        label: "Date of Birth",
        name: "birthday",
        type: "date",
        valid: "2006-10-23",
        dateFormat: "YYYY-MM-DD",
        placeholder: "",
        required: true,
      },
      {
        label: "Password",
        name: "password",
        type: "password",
        placeholder: "***********",
        required: true,
      },
      {
        label: "Confirm Password",
        name: "password_confirmation",
        type: "password",
        placeholder: "**********",
        required: true,
      },
    ],
  },
  {
    accountType: "joint",
    fields: [
      {
        label: "First Name - Applicant ONE",
        name: "first_name",
        type: "text",
        placeholder: "Tunde",
        required: true,
      },
      {
        label: "First Name - Applicant TWO",
        name: "first_name2",
        type: "text",
        placeholder: "Bola",
        required: true,
      },
      {
        label: "Middle Name - Applicant ONE",
        name: "middle_name",
        type: "text",
        placeholder: "Ayoola",
        required: false,
      },
      {
        label: "Middle Name - Applicant TWO",
        name: "middle_name2",
        type: "text",
        placeholder: "Ahmed",
        required: false,
      },
      {
        label: "Last Name - Applicant ONE",
        name: "last_name",
        type: "text",
        placeholder: "Fagbemi",
        required: true,
      },
      {
        label: "Last Name - Applicant TWO",
        name: "last_name2",
        type: "text",
        placeholder: "Tinubu",
        required: true,
      },
      {
        label: "Email Address - Applicant ONE",
        name: "email2",
        type: "email",
        placeholder: "ta***@****.com",
        required: true,
      },
      {
        label: "Email Address - Applicant TWO",
        name: "email2",
        type: "email",
        placeholder: "ta***@****.com",
        required: true,
      },
      {
        label: "Phone Number - Applicant ONE",
        name: "phone",
        type: "tel",
        placeholder: "+234**********",
        required: true,
      },
      {
        label: "Phone Number - Applicant TWO",
        name: "phone2",
        type: "tel",
        placeholder: "+234**********",
        required: true,
      },
      {
        label: "Nationality - Applicant ONE",
        name: "nationality",
        type: "text",
        placeholder: "Nigerian",
        required: true,
      },
      {
        label: "Nationality - Applicant TWO",
        name: "nationality2",
        type: "text",
        placeholder: "Nigerian",
        required: true,
      },
      {
        label: "Gender - Applicant ONE",
        name: "gender",
        type: "select",
        placeholder: "Male/Female",
        options: [
          {
            value: "male",
            label: "Male",
          },
          {
            value: "female",
            label: "Female",
          },
        ],
        required: true,
      },
      {
        label: "Gender - Applicant TWO",
        name: "gender2",
        type: "select",
        placeholder: "Male/Female",
        options: [
          {
            value: "male",
            label: "Male",
          },
          {
            value: "female",
            label: "Female",
          },
        ],
        required: true,
      },
      {
        label: "Date of Birth - Applicant ONE",
        name: "birthday",
        type: "date",
        valid: "2006-10-23",
        dateFormat: "YYYY-MM-DD",
        placeholder: "",
        required: true,
      },
      {
        label: "Date of Birth - Applicant TWO",
        name: "birthday2",
        type: "date",
        valid: "2006-10-23",
        dateFormat: "YYYY-MM-DD",
        placeholder: "",
        required: true,
      },
      {
        label: "Password",
        name: "password",
        type: "password",
        placeholder: "***********",
        required: true,
      },
      {
        label: "Confirm Password",
        name: "password_confirmation",
        type: "password",
        placeholder: "**********",
        required: true,
      },
    ],
  },
  {
    accountType: "corporate",
    fields: [
      {
        label: "Corporate Name",
        name: "company_name",
        type: "text",
        placeholder: "Dukia Precious Metals",
        required: true,
      },
      {
        label: "Company Type",
        name: "company_type",
        type: "select",
        placeholder: "Partnership",
        options: [
          {
            value: "public-listed-company",
            label: "Public Listed Company",
          },
          {
            value: "private-company",
            label: "Private Company",
          },
          {
            value: "partnership",
            label: "Partnership",
          },
          {
            value: "individual",
            label: "Individual/Sole Proprietor",
          },
          {
            value: "cooperative",
            label: "Cooperative",
          },
          {
            value: "trust",
            label: "Trust",
          },
        ],
        required: true,
      },
      {
        label: "Company TIN",
        name: "company_tax_identification_number",
        type: "text",
        placeholder: "**********-****",
        required: true,
      },
      {
        label: "Company Registration Number",
        name: "company_registration_number",
        type: "text",
        placeholder: "RC178290",
        required: true,
      },
      {
        label: "Date of Incorporation",
        name: "company_date_of_incorporation",
        type: "date",
        valid: "2024-10-23",
        dateFormat: "YYYY-MM-DD",
        placeholder: "2024-10-23",
        required: true,
      },
      {
        label: "Country of Incorporation",
        name: "company_country_of_incorporation",
        type: "text",
        placeholder: "Nigeria",
        required: true,
      },
      {
        label: "Registered Address",
        name: "company_registered_address",
        type: "text",
        placeholder: "3B, Olusola Olude Close, Gbagada Phase 2, Lagos",
        required: true,
      },
      {
        label: "Company Phone No.",
        name: "company_phone",
        type: "tel",
        placeholder: "+234********",
        required: true,
      },
      {
        label: "Company Email Address",
        name: "email",
        type: "email",
        placeholder: "company@dukia.com",
        required: true,
      },
      {
        label: "Contact Person Email Address",
        name: "company_contact_email",
        type: "email",
        placeholder: "person@dukia.com",
        required: true,
      },
      {
        label: "Contact Person Telephone No.",
        name: "company_contact_telephone",
        type: "tel",
        placeholder: "+234********",
        required: true,
      },
      {
        label: "Password",
        name: "password",
        type: "password",
        placeholder: "***********",
        required: true,
      },
      {
        label: "Confirm Password",
        name: "password_confirmation",
        type: "password",
        placeholder: "**********",
        required: true,
      },
    ],
  },
];
